Repository codeit-FE-15-Part4-Team1/RoamReady, pull requests merged in 2025-07, with the labels that each got.

#52 Fix: commit-lint 설정 수정
  commitlint.config.mjs
Labels: fix

#54 Feat: 로고 이미지 추가
  public/logos/logo-1-black.svg
  public/logos/logo-1-blue.svg
  public/logos/logo-1-white.svg
  public/logos/logo-2-black.svg
  public/logos/logo-2-blue.svg
  public/logos/logo-2-white.svg
  public/logos/logo-3-black.svg
  public/logos/logo-3-blue.svg
  public/logos/logo-3-white.svg
  public/logos/logo-symbol-black.svg
  public/logos/logo-symbol-blue.svg
  public/logos/logo-symbol-white.svg
Labels: feat

#70 Feat: Input 공통 컴포넌트
  .github/pull_request_template.md
  lefthook.yml
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/test/input/page.dev.tsx
  src/shared/components/ui/input/Example.tsx
  src/shared/components/ui/input/Field.tsx
  src/shared/components/ui/input/Helper.tsx
  src/shared/components/ui/input/Label.tsx
  src/shared/components/ui/input/Root.tsx
  src/shared/components/ui/input/Trigger.tsx
  src/shared/components/ui/input/context.ts
  src/shared/components/ui/input/index.ts
  src/shared/hooks/dummy
  src/shared/hooks/useImagePreview.ts
Labels: feat, chore

#86 Feat: Pagination 공통 컴포넌트
  pnpm-lock.yaml
  src/app/test/button/page.tsx
  src/app/test/pagination/page.dev.tsx
  src/shared/components/Button.tsx
  src/shared/components/ui/Pagination/index.tsx
Labels: feat

#65 Feat: Select 공통 컴포넌트 구현
  src/app/test/select/page.tsx
  src/shared/components/ui/select/SelectContent.tsx
  src/shared/components/ui/select/SelectContext.ts
  src/shared/components/ui/select/SelectItem.tsx
  src/shared/components/ui/select/SelectRoot.tsx
  src/shared/components/ui/select/SelectTrigger.tsx
  src/shared/components/ui/select/SelectValue.tsx
  src/shared/components/ui/select/index.ts
Labels: feat

#162 Feat: Logo icon 컴포넌트화
  public/icons/github-logo.svg
  public/logos/logo-1-black.svg
  public/logos/logo-1-blue.svg
  public/logos/logo-1-white.svg
  public/logos/logo-2-black.svg
  public/logos/logo-2-blue.svg
  public/logos/logo-2-white.svg
  public/logos/logo-3-black.svg
  public/logos/logo-3-blue.svg
  public/logos/logo-3-white.svg
  public/logos/logo-symbol-black.svg
  public/logos/logo-symbol-blue.svg
  public/logos/logo-symbol-white.svg
  src/app/assets/logos/logo-symbol.tsx
  src/app/assets/logos/logo-text-oneline.tsx
  src/app/assets/logos/logo-text-twoline.tsx
  src/app/assets/logos/logo.tsx
  src/app/test/logo/page.dev.tsx
  src/shared/components/layouts/footer/Footer.tsx
Labels: feat

#91 Feat: Header 공통 컴포넌트 구현
  public/icons/bell-dot.svg
  public/icons/bell.svg
  src/shared/components/layouts/header/AuthButton.tsx
  src/shared/components/layouts/header/AuthMenu.tsx
  src/shared/components/layouts/header/GuestMenu.tsx
  src/shared/components/layouts/header/Header.tsx
  src/shared/components/layouts/header/HeaderLogo.tsx
  src/shared/components/layouts/header/LogoLink.tsx
  src/shared/constants/dummy
  src/shared/constants/route.ts
  src/shared/types/dummy
  src/shared/types/icons.ts
Labels: feat, style

#186 Chore: Logo 컴포넌트화 폴더 구조 변경
  src/app/test/logo/page.dev.tsx
  src/shared/assets/logos/logo-symbol.svg
  src/shared/assets/logos/logo-symbol.tsx
  src/shared/assets/logos/logo-text-oneline.svg
  src/shared/assets/logos/logo-text-oneline.tsx
  src/shared/assets/logos/logo-text-twoline.svg
  src/shared/assets/logos/logo-text-twoline.tsx
  src/shared/assets/logos/logo.svg
  src/shared/assets/logos/logo.tsx
  src/shared/components/layouts/footer/Footer.tsx
  src/shared/components/layouts/header/LogoLink.tsx
Labels: fix, chore

#201 Chore: 테스트 페이지 파일명 일괄 수정
  src/app/test/bottom-sheet/page.dev.tsx
  src/app/test/button/page.dev.tsx
  src/app/test/select/page.dev.tsx
Labels: chore

#190 Feat: Avatar 공통 컴포넌트 및 수정 가능한 Avatar 기능 구현
  .npmrc
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/test/avatar/page.dev.tsx
  src/domain/User/components/AvatarEditButton.tsx
  src/domain/User/components/EditableAvatar.tsx
  src/domain/User/components/dummy
  src/domain/User/hooks/dummy
  src/domain/User/hooks/useProfileImageMutation.ts
  src/shared/components/constants/image.ts
  src/shared/components/ui/avatar/index.tsx
  src/shared/hooks/useImageCompression.ts
Labels: feat

#198 Feat: Nothing UI 구현
  src/app/test/logo/page.dev.tsx
  src/app/test/nothing/page.dev.tsx
  src/shared/assets/logos/LogoSymbol.tsx
  src/shared/components/ui/Pagination/index.tsx
  src/shared/components/ui/nothing/index.tsx
Labels: feat, style

#168 Feat: 예약 달력 구현
  package.json
  pnpm-lock.yaml
  src/app/test/reservation-calendar/page.dev.tsx
  src/domain/Reservation/components/dummy
  src/domain/Reservation/components/reservation-calendar/CalendarHeader.tsx
  src/domain/Reservation/components/reservation-calendar/DayCell.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationCalendar.tsx
  src/domain/Reservation/constants/dummy
  src/domain/Reservation/hooks/useCalendar.ts
  src/domain/Reservation/types/event.ts
  src/domain/Reservation/utils/reservation.ts
  src/shared/components/ui/avatar/index.tsx
  src/shared/components/ui/code-block/index.tsx
Labels: feat

#172 Feat: ReviewCard 컴포넌트
  src/app/globals.css
  src/app/test/review-card/page.dev.tsx
  src/domain/Activity/components/detail/ReviewCard.tsx
  src/domain/Activity/components/main/dummy
  src/domain/Activity/types/detail/types.ts
  src/domain/Activity/types/main/dummy
  src/domain/Activity/utils/dummy
  src/domain/Activity/utils/getTimeAgo.ts
Labels: feat

#175 Feat: form validation setup (RHF+zod resolver)
  package.json
  pnpm-lock.yaml
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/test/input/page.dev.tsx
  src/app/test/logo/page.dev.tsx
  src/domain/Auth/components/OAuth.tsx
  src/domain/Auth/components/SignInForm.tsx
  src/domain/Auth/components/SignUpForm.tsx
  src/domain/Auth/components/dummy
  src/domain/Auth/constants/dummy
  src/domain/Auth/schemas/auth.schemas.ts
  src/domain/Auth/schemas/request.ts
  src/domain/Auth/schemas/response.ts
  src/domain/Auth/services/auth.services.ts
  src/domain/Auth/services/index.ts
  src/shared/assets/logos/Logo.tsx
  src/shared/assets/logos/LogoTextOneline.tsx
  src/shared/assets/logos/LogoTextTwoline.tsx
  src/shared/components/layouts/footer/Footer.tsx
  src/shared/components/layouts/header/LogoLink.tsx
  src/shared/components/ui/input/Field.tsx
  src/shared/components/ui/input/Helper.tsx
  src/shared/components/ui/input/InputContext.ts
  src/shared/components/ui/input/InputExample.tsx
  src/shared/components/ui/input/InputField.tsx
  src/shared/components/ui/input/InputHelper.tsx
  src/shared/components/ui/input/InputLabel.tsx
  src/shared/components/ui/input/InputRoot.tsx
  src/shared/components/ui/input/InputTrigger.tsx
  src/shared/components/ui/input/Label.tsx
  src/shared/components/ui/input/Root.tsx
  src/shared/components/ui/input/context.ts
  src/shared/components/ui/input/index.ts
  src/shared/constants/endpoints.ts
  src/shared/constants/routes.ts
  src/shared/hooks/useImagePreview.ts
  src/shared/schemas/dummy
  src/shared/schemas/error.ts
Labels: feat

#222 Feat: 쿠키 설정, 미들웨어 및 인증 클라이언트 정비
  pnpm-lock.yaml
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signout/route.ts
  src/app/api/auth/signup/route.ts
  src/domain/Auth/components/SignInForm.tsx
  src/domain/Auth/components/SignUpForm.tsx
  src/domain/Auth/libs/authApiClient.ts
  src/domain/Auth/libs/dummy
  src/domain/Auth/services/index.ts
  src/middleware.ts
  src/shared/components/layouts/header/GuestMenu.tsx
  src/shared/components/layouts/header/LogoLink.tsx
  src/shared/components/ui/input/InputLabel.tsx
  src/shared/components/ui/nothing/index.tsx
  src/shared/constants/bridgeEndpoints.ts
  src/shared/constants/endpoints.ts
  src/shared/constants/route.ts
  src/shared/constants/routes.ts
  src/shared/hooks/useSignout.ts
  src/shared/libs/apiClient.ts
Labels: feat

#272 Feat: MyPageMenu 구현 및 기타 경로/레이아웃 수정
  .vscode/settings.json
  public/images/image-activity-1.jpg
  public/images/image-activity-10.jpg
  public/images/image-activity-11.jpg
  public/images/image-activity-12.jpg
  public/images/image-activity-13.jpg
  public/images/image-activity-14.jpg
  public/images/image-activity-15.jpg
  public/images/image-activity-16.jpg
  public/images/image-activity-17.jpg
  public/images/image-activity-18.jpg
  public/images/image-activity-2.jpg
  public/images/image-activity-3.jpg
  public/images/image-activity-4.jpg
  public/images/image-activity-5.jpg
  public/images/image-activity-6.jpg
  public/images/image-activity-8.jpg
  public/images/image-activity-9.jpg
  src/app/(app)/layout.tsx
  src/app/(app)/mypage/info/page.tsx
  src/app/(app)/mypage/layout.tsx
  src/app/(app)/mypage/page.tsx
  src/app/(app)/page.tsx
  src/app/test/avatar/page.dev.tsx
  src/domain/Activity/components/detail/kakao-map/KaKaoMap.tsx
  src/domain/Activity/components/main/ActivityCard.tsx
  src/domain/Activity/schemas/main/index.ts
  src/domain/Activity/types/main/activities.ts
  src/domain/Reservation/components/card/ReservationCard.tsx
  src/domain/User/components/icons/ExperiencesIcon.tsx
  src/domain/User/components/icons/InfoIcon.tsx
  src/domain/User/components/icons/ReservationsIcon.tsx
  src/domain/User/components/icons/ReservationsStatusIcon.tsx
  src/domain/User/components/icons/index.ts
  src/domain/User/components/ui/AvatarEditButton.tsx
  src/domain/User/components/ui/EditableAvatar.tsx
  src/domain/User/components/ui/MyPageMenu.tsx
  src/domain/User/constants/menuItems.ts
  src/domain/User/hooks/useMyPageMenu.ts
  src/shared/components/ui/avatar/index.tsx
  src/shared/components/ui/loading-spinner/index.tsx
  src/shared/constants/routes.ts
Labels: feat

#324 Feat: OAuth 구현
  .vscode/settings.json
  public/favicon.ico
  src/app/(app)/layout.tsx
  src/app/_components/AuthStatusProvider.tsx
  src/app/_components/ClientProvider.tsx
  src/app/api/auth/kakao/callback/route.ts
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signout/route.ts
  src/app/api/auth/signup/route.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/domain/Auth/components/OAuth.tsx
  src/domain/Auth/services/index.ts
  src/domain/Auth/utils/setAuthCookies.ts
  src/domain/User/hooks/useMyPageMenu.ts
  src/middleware.ts
  src/shared/components/layouts/header/Header.tsx
  src/shared/utils/dummy
  src/shared/utils/errors/kyHttpErrorGuards.ts
  src/shared/utils/getCookieValue.ts
Labels: feat, urgent PR

#275 Feat: 체험 상세페이지 UI
  public/icons/triangle-arrow.tsx
  public/mock/mock-1.png
  public/mock/mock-2.png
  public/mock/mock-3.jpeg
  public/mock/mock-4.png
  public/mock/mock-5.png
  src/app/(app)/activities/[id]/page.tsx
  src/app/test/reservation/page.dev.tsx
  src/app/test/review-card/page.dev.tsx
  src/domain/Activity/components/detail/Reservation/AvailableTimeSection.tsx
  src/domain/Activity/components/detail/Reservation/DateSelectSection.tsx
  src/domain/Activity/components/detail/Reservation/HeadCount.tsx
  src/domain/Activity/components/detail/Reservation/ParticipationSection.tsx
  src/domain/Activity/components/detail/Reservation/ReservationMobile.tsx
  src/domain/Activity/components/detail/Reservation/ReservationPC.tsx
  src/domain/Activity/components/detail/Reservation/ReservationTablet.tsx
  src/domain/Activity/components/detail/Review/ReviewCard.tsx
  src/domain/Activity/components/detail/Review/ReviewSection.tsx
  src/domain/Activity/components/detail/activity-img/ActivityImg.tsx
  src/domain/Activity/components/detail/activity-summary/ActivityDropdown.tsx
  src/domain/Activity/components/detail/activity-summary/ActivitySummary.tsx
  src/domain/Activity/components/detail/description/DescriptionSection.tsx
  src/domain/Activity/components/detail/mock/mock-data.ts
  src/domain/Activity/components/detail/responsive-wrappers/ActivitySummaryWrapper.tsx
  src/domain/Activity/components/detail/responsive-wrappers/ReservationWrapper.tsx
  src/domain/Activity/hooks/detail/useReservationForm.ts
  src/domain/Activity/types/detail/types.ts
  src/domain/Reservation/components/reservation-calendar/CalendarHeader.tsx
  src/shared/assets/icons/TriangleArrow.tsx
  src/shared/components/ui/date-picker/DatePickerDate.tsx
  src/shared/components/ui/date-picker/DatePickerMonth.tsx
  src/shared/components/ui/dropdown/DropdownItem.tsx
  src/shared/components/ui/dropdown/DropdownRoot.tsx
  src/shared/constants/breakpoints.ts
Labels: feat, style

#367 Feat: 예약 현황 달력 api 연결
  src/app/(app)/mypage/reservations-status/page.tsx
  src/app/api/my-activities/[activityId]/reservation-dashboard/route.ts
  src/app/api/my-activities/[activityId]/reservations/[reservationId]/route.ts
  src/app/api/my-activities/api.ts
  src/app/api/my-reservations/route.ts
  src/app/test/reservation-calendar/page.dev.tsx
  src/domain/Reservation/components/reservation-calendar/DayCell.tsx
  src/domain/Reservation/components/reservation-calendar/DayCellBottomSheet.tsx
  src/domain/Reservation/components/reservation-calendar/DayCellPopover.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationCalendar.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationDashboard.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationDetail.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationSelect.tsx
  src/domain/Reservation/hooks/useCalendar.ts
  src/domain/Reservation/mock/reservation.ts
  src/domain/Reservation/services/reservation-calendar/index.ts
  src/domain/Reservation/types/dummy
  src/domain/Reservation/types/reservation.ts
  src/domain/Reservation/utils/reservation.ts
  src/shared/components/ui/select/SelectItem.tsx
  src/shared/constants/endpoints.ts
Labels: feat

#399 Fix: 데이터 못 불러오는 구조 수정
  src/app/api/activities/[id]/available-schedule/route.ts
  src/domain/Reservation/components/reservation-calendar/DayCell.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationDetail.tsx
Labels: fix

#415 Refactor: 1차 리팩토링
  src/app/api/auth/kakao/callback/route.ts
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signup/route.ts
  src/domain/Auth/components/SignInForm.tsx
  src/domain/Auth/components/SignUpForm.tsx
  src/domain/Auth/hooks/useUser.ts
  src/domain/Auth/schemas/response.ts
  src/domain/Auth/utils/handleSignin.ts
  src/domain/Auth/utils/setAuthCookies.ts
  src/middleware.ts
  src/shared/components/ui/input/InputTrigger.tsx
  src/shared/components/ui/toast/ToastContainer.tsx
  src/shared/utils/errors/handleApiError.ts
Labels: refactor

#419 QA 사항 1차 반영
  src/app/(app)/activities/page.tsx
  src/app/(app)/mypage/layout.tsx
  src/app/(app)/mypage/reservations-status/page.tsx
  src/app/api/auth/kakao/callback/route.ts
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signup/route.ts
  src/domain/Activity/components/main/ActivityCard/ActivityCardSkeleton.tsx
  src/domain/Activity/components/main/ActivityCard/LikeButton.tsx
  src/domain/Activity/components/main/ActivityCard/index.tsx
  src/domain/Activity/components/main/ActivityFilter/index.tsx
  src/domain/Activity/components/main/ActivitySearch/ActivitySearchBar.tsx
  src/domain/Activity/components/main/ActivitySection/ActivityCarousel.client.tsx
  src/domain/Activity/components/main/ActivitySection/ActivityCarousel.tsx
  src/domain/Activity/components/main/ActivitySection/ActivitySection.client.tsx
  src/domain/Activity/components/main/ActivitySection/ActivitySection.tsx
  src/domain/Activity/components/main/ActivitySection/CarouselSkeleton.tsx
  src/domain/Activity/components/main/ActivitySection/SectionSkeleton.tsx
  src/domain/Activity/hooks/main/useResponsiveSize.ts
  src/domain/Activity/services/main/getActivities.ts
  src/domain/Auth/components/SignInForm.tsx
  src/domain/Auth/components/SignUpForm.tsx
  src/domain/Auth/hooks/useUser.ts
  src/domain/Auth/schemas/response.ts
  src/domain/Auth/utils/handleSignin.ts
  src/domain/Auth/utils/setAuthCookies.ts
  src/domain/Reservation/components/reservation-calendar/DayCell.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationDashboard.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationSelect.tsx
  src/domain/User/components/create-activity/CategoryInput.tsx
  src/domain/User/components/create-activity/DescriptionInput.tsx
  src/domain/User/components/create-activity/LocationInput.tsx
  src/domain/User/components/create-activity/PriceInput.tsx
  src/domain/User/components/create-activity/SubmitButton.tsx
  src/domain/User/components/create-activity/TimeSlotInput/TimeSlotHeader.tsx
  src/domain/User/components/create-activity/TimeSlotInput/TimeSlotRow.tsx
  src/domain/User/constants/createActivity.ts
  src/domain/User/hooks/create-activity/useActivityForm.ts
  src/middleware.ts
  src/shared/components/ui/input/InputTrigger.tsx
  src/shared/components/ui/toast/ToastContainer.tsx
  src/shared/libs/queryClient.ts
  src/shared/utils/errors/handleApiError.ts
Labels: chore
