Repository codeit-FE-15-Part4-Team1/RoamReady, pull requests merged in 2025-08, with the labels that each got.

#423 Refactor: 1차 QA 사항 반영
  src/app/(app)/activities/[id]/loading.tsx
  src/app/(app)/activities/[id]/page.tsx
  src/app/(app)/error.tsx
  src/app/(search)/_components/SearchHeader.tsx
  src/app/error.tsx
  src/app/global.css
  src/app/test/logo/page.dev.tsx
  src/domain/Activity/actions/detail/reserve.ts
  src/domain/Activity/components/detail/Reservation/AvailableTimeSection.tsx
  src/domain/Activity/components/detail/Reservation/ReservationMobile.tsx
  src/domain/Activity/components/detail/Reservation/ReservationPC.tsx
  src/domain/Activity/components/detail/Reservation/ReservationTablet.tsx
  src/domain/Activity/components/detail/Review/ExpandableReview.tsx
  src/domain/Activity/components/detail/Review/ReviewCard.tsx
  src/domain/Activity/components/detail/Review/ReviewSection.tsx
  src/domain/Activity/components/detail/activity-img/ActivityImg.tsx
  src/domain/Activity/components/detail/activity-img/ImageModal.tsx
  src/domain/Activity/components/detail/description/DescriptionSection.tsx
  src/domain/Activity/components/detail/kakao-map/KaKaoMap.tsx
  src/domain/Activity/components/detail/kakao-map/MapMarker.tsx
  src/domain/Activity/components/detail/kakao-map/MapSectopn.tsx
  src/domain/Activity/components/detail/responsive-wrappers/ReservationWrapper.tsx
  src/domain/Activity/components/detail/skeleton/ActivityDescriptionSkeleton.tsx
  src/domain/Activity/components/detail/skeleton/ActivityImgSkeleton.tsx
  src/domain/Activity/components/detail/skeleton/ActivitySummarySkeleton.tsx
  src/domain/Activity/components/detail/skeleton/KaKaoMapSkeleton.tsx
  src/domain/Activity/components/detail/skeleton/KaKaoSkeleton.tsx
  src/domain/Activity/components/detail/skeleton/ReservationSkeleton.tsx
  src/domain/Activity/components/detail/skeleton/ReviewSkeleton.tsx
  src/domain/Notification/components/Notification.tsx
  src/domain/Notification/components/NotificationCard.tsx
  src/domain/Notification/components/NotificationDelete.tsx
  src/domain/Notification/components/PopoverOpenEffect.tsx
  src/domain/Notification/mock/mock.ts
  src/domain/Reservation/components/reservation-calendar/CalendarHeader.tsx
  src/domain/User/components/create-activity/TimeSlotInput/TimeSlotHeader.tsx
  src/domain/User/components/create-activity/TimeSlotInput/TimeSlotRow.tsx
  src/shared/components/Button.tsx
  src/shared/components/layouts/header/AuthMenu.tsx
  src/shared/components/ui/Pagination/index.tsx
  src/shared/components/ui/dialog/DialogContent.tsx
  src/shared/components/ui/dialog/DialogFooter.tsx
  src/shared/components/ui/dialog/DialogOverlay.tsx
  src/shared/hooks/useClipboard.ts
  src/shared/hooks/useImagePreview.ts
  src/shared/slices/notificationSlice.ts
  src/shared/store/index.ts
Labels: refactor

#434 Chore: 스토리북 설치
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  src/stories/Button.stories.ts
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/header.css
  src/stories/page.css
  vitest.config.ts
  vitest.shims.d.ts
Labels: chore

#457 Refactor: 2차 QA 반영
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/app/(app)/mypage/experiences/page.tsx
  src/app/(app)/mypage/info/page.tsx
  src/app/(app)/mypage/layout.tsx
  src/app/(app)/mypage/reservations-status/page.tsx
  src/app/(app)/mypage/reservations/page.tsx
  src/app/test/avatar/page.dev.tsx
  src/domain/Activity/libs/main/dummy
  src/domain/Reservation/components/header/index.tsx
  src/domain/Reservation/components/my-activity-section/MyActivitySection.tsx
  src/domain/Reservation/components/reservation-card/ReservationActionButton.tsx
  src/domain/Reservation/components/reservation-card/ReservationCard.tsx
  src/domain/Reservation/components/reservation-card/WriteReviewModal.tsx
  src/domain/Reservation/components/reservation-section/ReservationSection.tsx
  src/domain/Reservation/components/reservation-section/ReservationStatusFilter.tsx
  src/domain/Reservation/components/skeleton/ReservationSectionSkeleton.tsx
  src/domain/Reservation/constants/index.ts
  src/domain/User/components/form/EditUserInfoForm.tsx
  src/domain/User/components/ui/AvatarEditButton.tsx
  src/domain/User/components/ui/EditableAvatar.tsx
  src/domain/User/components/ui/MyPageMenu.tsx
  src/shared/components/layouts/header/AuthMenu.tsx
  src/shared/components/ui/avatar/index.tsx
  src/shared/components/ui/dialog/DialogContent.tsx
  src/shared/components/ui/nothing/index.tsx
  src/shared/constants/routes.ts
Labels: feat, refactor

#461 Refactor: 리팩토링3
  src/app/(app)/layout.tsx
  src/app/(auth)/signin/page.tsx
  src/app/api/auth/kakao/callback/route.ts
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signout/route.ts
  src/app/api/auth/signup/route.ts
  src/domain/Auth/components/OAuth.tsx
  src/domain/Auth/components/SignInForm.tsx
  src/domain/Auth/components/SignUpForm.tsx
  src/domain/Auth/hooks/useSigninMutation.ts
  src/domain/Auth/hooks/useSignupMutation.ts
  src/domain/Auth/schemas/request.ts
  src/middleware.ts
  src/shared/components/ui/error-fallback/index.tsx
  src/shared/components/ui/toast/Toast.tsx
  src/shared/components/ui/toast/ToastContainer.tsx
  src/shared/constants/bridgeEndpoints.ts
  src/shared/slices/toastSlice.ts
Labels: fix, feat, refactor

#463 Feat: 스토리북 공통 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/shared/components/ui/popover/PopoverRoot.tsx
  src/shared/components/ui/tabs/TabsRoot.tsx
  src/stories/Avatar.stories.ts
  src/stories/BottomSheet.stories.tsx
  src/stories/Dialog.stories.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Input.stories.tsx
  src/stories/LoadingSpinner.stories.ts
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/Popover.stories.tsx
  src/stories/Select.stories.tsx
  src/stories/Tabs.stories.tsx
  src/stories/Toast.stories.ts
  src/stories/header.css
  src/stories/page.css
Labels: feat

#464 Refactor: 2차 QA내용 반영
  src/app/(app)/mypage/experiences/create/page.tsx
  src/app/(app)/mypage/experiences/edit/[id]/page.tsx
  src/domain/Reservation/components/reservation-calendar/CalendarHeaderSkeleton.tsx
  src/domain/Reservation/components/reservation-calendar/DayCell.tsx
  src/domain/Reservation/components/reservation-calendar/DayCellSkeleton.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationDetail.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationSkeleton.tsx
  src/domain/Reservation/hooks/useCalendar.ts
  src/domain/User/components/create-activity/CreateActivityForm.tsx
  src/domain/User/components/create-activity/CreateFormSkeleton.tsx
Labels: refactor

#470 Feat: 메인페이지 검색 기능 구현 완료
  src/app/(search)/_components/SearchHeader.tsx
  src/app/(search)/layout.tsx
  src/app/(search)/search/page.tsx
  src/app/api/etl/route.ts
  src/domain/Activity/components/main/ActivityCarousel.tsx
  src/domain/Activity/components/main/ActivityFilter/ActivityFilterSkeleton.tsx
  src/domain/Activity/components/main/ActivitySearch/ActivitySearchBar.tsx
  src/domain/Activity/components/main/ActivitySearch/ActivitySearchField.tsx
  src/domain/Activity/components/main/ActivitySearch/ActivitySearchForm.tsx
  src/domain/Activity/components/main/ActivitySearch/DebouncedInput.tsx
  src/domain/Activity/components/main/ActivitySection/ActivityCarousel.tsx
  src/domain/Activity/components/main/ActivitySection/ActivitySection.client.tsx
  src/domain/Activity/hooks/main/useEtlActivities.ts
  src/domain/Activity/hooks/main/useInfiniteActivities.ts
  src/domain/Activity/schemas/main/index.ts
  src/domain/Activity/services/main/getEtlActivities.ts
  src/middleware.ts
Labels: feat

#503 Refactor: 3차 QA내용 반영
  src/app/(app)/mypage/reservations-status/page.tsx
  src/app/api/my-activities/api.ts
  src/domain/Activity/components/main/ActivityFilter/SortSelect.tsx
  src/domain/Reservation/components/reservation-calendar/DayCell.tsx
  src/domain/Reservation/components/reservation-calendar/ReservationDetail.tsx
  src/domain/User/components/create-activity/CategoryInput.tsx
  src/domain/User/components/create-activity/TimeSlotInput/TimeSlotRow.tsx
  src/domain/User/hooks/create-activity/useActivityForm.ts
  src/shared/components/ui/select/SelectValue.tsx
Labels: refactor

#511 Fix: 예약 거절 시 캐시 무효화
  .storybook/main.ts
  package.json
  src/app/storybook/page.tsx
  src/domain/Activity/components/detail/activity-summary/ActivityDropdown.tsx
  src/domain/Reservation/components/my-activity-card/DeleteMyActivityModal.tsx
  src/domain/Reservation/components/reservation-calendar/DayCell.tsx
  vercel.json
Labels: fix

#557 Fix: 리드미 업데이트 및 탭키 수정
  README.md
  src/app/api/auth/kakao/callback/route.ts
  src/app/global.css
  src/domain/Auth/actions/dummy
  src/domain/Auth/types/dummy
  src/shared/components/ui/input/InputTrigger.tsx
Labels: fix, documentation, style

#559 Fix: 불필요한 401 방지
  src/app/_components/AuthInitializer.tsx
  src/domain/Auth/hooks/useUser.ts
Labels: fix

#561 Fix: 로그인 시 헤더 즉각 업데이트
  src/domain/Auth/hooks/useSigninMutation.ts
Labels: fix
